apiVersion: v1
kind: Service
metadata:
  name: myapp
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8081'
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: 8081
    targetPort: myapp-port
    protocol: TCP
  selector:
    app: myapp
  type: NodePort

