apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: tiagotele/golangsample:2.0
        ports:
        - name: myapp-port
          containerPort: 8080
        volumeMounts:
        - name: myapp-volume
          mountPath: /etc/creds
          readOnly: true
      volumes:
        - name: myapp-volume
          secret:
            secretName: my-app-secrets
        #   configMap:
        #     name : my-configmap
