apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: sample
spec:
  containers:
  - name: k8s-demo
    image: tiagotele/golangsample:2.0
    ports:
    - name: myapp-port
      containerPort: 8080
