name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: actions/checkout@v3
        env:
          DOCKER_USER: ${{sercrets.DOCKER_HUB_USER}}
          DOCKER_PASSWORD: ${{sercrets.DOCKER_HUB_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSOWRD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tiagotele/golangsample:$(date +%s)
      - name: Docker push
        run: docker push tiagotele/golangsample
